version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
        SA_PASSWORD: "Pass@word"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"

  distributedservices.core:
    image: ${DOCKER_REGISTRY-masivian}/distributedservices.core:${PLATFORM:-linux}-${TAG:-latest}
    container_name: DistributedServices.Core
    environment:
        SQL_SERVER_CONNECTION: "Server=sqldata; Database=MasivianDb; User=sa; Password=Pass@word;"
    build:
      context: .
      dockerfile: DistributedServices.Core/Dockerfile
    ports:
        - "5200:80"
    depends_on:
        - sqldata
